### ISSUE TITLE
你好 请问sessionId和门的id怎么取

### ISSUE THREAD

**Issue by dadyxuan** [MrTaoSix/qinlinopen#1]
你好 请问sessionId和门的id怎么取

**Comment by MrTaoSix** [comment]
这个很久以前的东西了，是通过Charles 抓包工具抓去微信小程序的请求信息获取
















在 2022-09-14 11:33:20，"xxxxuanya" ***@***.***> 写道：

你好 请问sessionId和门的id怎么取

**Comment by dadyxuan** [comment]
好的啊哈哈哈哈
